-- ONSTOOD Knowledge: consent independent from visibility, quality/PII metadata,
-- post contributions, safe internal retrieval. Applied to production on 2026-08-27.
-- The live database migration history is authoritative; this file mirrors the release design.

-- Documents now support Public separately from ONSTOOD Knowledge consent.
alter table public.documents drop constraint if exists documents_visibility_check;
alter table public.documents add constraint documents_visibility_check
check (visibility = any (array['private'::text,'connections'::text,'public'::text,'onstood_ai'::text]));

-- Wall/Post Knowledge registry.
create table if not exists public.onstood_knowledge_posts (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null unique references public.posts(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  source_scope text not null default 'onstood_only',
  external_ai_allowed boolean not null default false,
  quality_status text not null default 'pending_review',
  knowledge_type text not null default 'unclassified',
  confidence_score numeric(5,4),
  pii_status text not null default 'pending',
  attribution_mode text not null default 'anonymous',
  review_notes text,
  contributed_at timestamptz not null default now(),
  revoked_at timestamptz,
  reviewed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.onstood_knowledge_post_chunks (
  id bigint generated by default as identity primary key,
  knowledge_post_id uuid not null references public.onstood_knowledge_posts(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  safe_content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  fts tsvector generated always as (to_tsvector('simple', coalesce(safe_content,''))) stored,
  unique (knowledge_post_id, chunk_index)
);

-- Note: full production constraints, RLS, PII helpers and search RPC were applied
-- through Supabase migrations in this session. Do not re-run this mirror file blindly
-- on production without comparing migration history first.
